name: Trigger auto deployment for azure-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '"./Dockerfile"/**'
    - '.github/workflows/azure-app-AutoDeployTrigger-fe15d67a-de34-45e7-83ac-035b264a7e43.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: jagorddemo.azurecr.io
          username: ${{ secrets.AZUREAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.AZUREAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jagorddemo.azurecr.io/prod-deploy:${{ github.sha }}
          file: "./Dockerfile"/Dockerfile
          context: "./Dockerfile"/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZUREAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n azure-app -g container-app --server jagorddemo.azurecr.io --username  ${{ secrets.AZUREAPP_REGISTRY_USERNAME }} --password ${{ secrets.AZUREAPP_REGISTRY_PASSWORD }}
            az containerapp update -n azure-app -g container-app --image jagorddemo.azurecr.io/prod-deploy:${{ github.sha }}
