name: Linux Container Node Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistry543456.azurecr.io
          username: ${{ secrets.AZUREAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.AZUREAPP_REGISTRY_PASSWORD }}
