on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
        - name: Get tag
          id: tag
       
        - name: Log into registry
        
          uses: docker/login-action@v1
          with:
           registry: ${{ secrets.ACR_ENDPOINT }}
           username: ${{ secrets.ACR_USERNAME }}
           password: ${{ secrets.ACR_PASSWORD }}
      
